version: '3'
services:
  # The load balancer
  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 2701
      - 2702
      - 2703

  echo:
    image: cjimti/go-echo
    command: ["-text", "echo"]
    environment:
      TCP_PORT: 2700
    ports:
      - 2700